plugins {
	id 'java'
	id 'application'
}

application {
	mainClass = 'com.mango.products.ProductsApplication'
}

jar {
	manifest {
		attributes 'Main-Class': application.mainClass
	}
}

group = 'com.mango'
version = '0.0.1-SNAPSHOT'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(21)
	}
}

repositories {
	mavenCentral()
}

dependencies {
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.named('test') {
	useJUnitPlatform()
}
