version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: product-api
    ports:
      - "8080:8080"
    command: ["java", "-jar", "app.jar"]
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M

  benchmark:
    build:
      context: .
      dockerfile: Dockerfile.benchmark
    container_name: product-benchmark
    depends_on:
      - app
    command: sh -c "chmod +x /app/benchmark.sh && /app/benchmark.sh"
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '0.25'
          memory: 256M