spring:
  application:
    name: products

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/products}
    username: ${DB_USERNAME:products}
    password: ${DB_PASSWORD:products}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: false

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: never

logging:
  level:
    org.springframework: INFO
    com.mango: DEBUG
